---
title: "simple_example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{simple_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r color, echo = FALSE, results='asis'}
# crayon needs to be explicitly activated in Rmd
options(crayon.enabled = TRUE)
# Hooks needs to be set to deal with outputs
# thanks to fansi logic
if(requireNamespace("fansi", quietly = TRUE)) {
  old_hooks <- fansi::set_knit_hooks(knitr::knit_hooks, 
                                     which = c("output", "message", "error"))
}
```


```{r setup}
library(slimr)
```


```
initialize() {
  initializeMutationRate(1e-7);
  initializeMutationType("m1", 0.5, "f", 0.0);
  initializeGenomicElementType("g1", m1, 1.0);
  initializeGenomicElement(g1, 0, 99999);
  initializeRecombinationRate(1e-8);
}

1 {
  for (i in 1:3)
    sim.addSubpop(i, 1000);
  subpops = sim.subpopulations;
  lines = readFile("~/Desktop/migration.csv");
  lines = lines[substr(lines, 0, 1) != "//"];
  for (line in lines)
  {
    fields = strsplit(line, ",");
    i = asInteger(fields[0]);
    j = asInteger(fields[1]);
    m = asFloat(fields[2]);
    if (i != j)
    {
      p_i = subpops[subpops.id == i];
      p_j = subpops[subpops.id == j];
      p_j.setMigrationRates(p_i, m);
    }
  }
}

10000 late() { sim.outputFull(); }

```

```{r script}
slim_script(
  slim_block(initialize(), {
    initializeMutationRate(1e-7);
    initializeMutationType("m1", 0.5, "f", 0.0);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99999);
    initializeRecombinationRate(1e-8);
  }),
  slim_block(1, {
    for (i in 1:3) {
      sim.addSubpop(i, 1000);
    }
    subpops = sim.subpopulations;
    lines = readFile("~/Desktop/migration.csv");
    lines = lines[substr(lines, 0, 1) != "//"];
    for (line in lines) {
      fields = strsplit(line, ",");
      i = asInteger(fields[0]);
      j = asInteger(fields[1]);
      m = asFloat(fields[2]);
      if (i != j) {
        p_i = subpops[subpops.id == i];
        p_j = subpops[subpops.id == j];
        p_j.setMigrationRates(p_i, m);
      }
    }
  }),
  slim_block(10000, late(), {
    sim.outputFull();
  })
) -> script_1

script_1

```

```{r script_2}

disp_mat <- matrix(c(1, 1, 0.78, 
                     1, 2, 0.1, 
                     1, 3, 0.12, 
                     2, 1, 0.01, 
                     2, 2, 0.96, 
                     2, 3, 0.03, 
                     3, 1, 0.33, 
                     3, 2, 0.17, 
                     3, 3, 0.5),
                   ncol = 3, byrow = TRUE)

slim_script(
  slim_block(initialize(), {
    initializeMutationRate(1e-7);
    initializeMutationType("m1", 0.5, "f", 0.0);
    initializeGenomicElementType("g1", m1, 1.0);
    initializeGenomicElement(g1, 0, 99999);
    initializeRecombinationRate(1e-8);
  }),
  slim_block(1, {
    for (i in 1:3) {
      sim.addSubpop(i, 1000);
    }
    subpops = sim.subpopulations;
    
    disp_mat = slimr_inline(disp_mat)
    
    for (line in seqLen(nrow(disp_mat))) {
      i = asInteger(disp_mat[line, 0]);
      j = asInteger(disp_mat[line, 1]);
      m = asFloat(disp_mat[line, 2]);
      if (i != j) {
        p_i = subpops[subpops.id == i];
        p_j = subpops[subpops.id == j];
        p_j.setMigrationRates(p_i, m);
      }
    }
  }),
  slim_block(10000, late(), {
    slimr_output(sim.subpopulations.genomes%.%.G$outputVCF(), "final_output");
  })
) -> script_2

script_2

```
We can see that the whole matrix has been embedded in the SLiM script by running `as_slim_text` on this `slimr_script` object. This is the script that will actually be run by SLiM.

```{r show_script}
cat(as_slim_text(script_2))
```

Now let's see if we can run it.

```{r run_script}
tfile <- tempfile()
results <- slim_run(script_2, capture_output = "tempfile")

```
