on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}-${{ matrix.config.r }}-slim-${{ matrix.config.slim }}-conda-${{ matrix.config.conda }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release', slim: 'yes', conda: 'no'}
          - {os: windows-latest, r: 'release', slim: 'no', conda: 'no'}
          - {os: macOS-latest, r: 'release', slim: 'yes', conda: 'no'}
          - {os: macOS-latest, r: 'devel', slim: 'yes', conda: 'no'}
          - {os: macOS-latest, r: 'release', slim: 'no', conda: 'yes'}
          - {os: ubuntu-20.04, r: 'release', slim: 'yes', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest", conda: 'no'}
          - {os: ubuntu-20.04, r: 'release', slim: 'no', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest", conda: 'yes'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_PAT: ${{ secrets.INSTALL_GITHUB_PAT }}
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSYS2 on Windows
        if: runner.os == 'Windows' && matrix.config.slim == 'yes' && steps.cache-slim.outputs.cache-hit != 'true'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
           git
           unzip
           base-devel
           msys2-devel
           mingw-w64-x86_64-toolchain
           mingw-w64-x86_64-cmake

      - name: Download SLiM on Windows
        if: runner.os == 'Windows' && matrix.config.slim == 'yes'
        shell: msys2 {0}
        run: |
          cd /d/a
          wget http://benhaller.com/slim/SLiM.zip

      - name: Download SLiM on non-Windows
        if: runner.os != 'Windows' && matrix.config.slim == 'yes'
        run: |
          cd ${{ github.workspace }}
          wget http://benhaller.com/slim/SLiM.zip

      # - name: Cache SLiM on Windows
      #   id: cache-slim-win
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ${{ github.workspace }}/SLiM_build
      #       ${{ github.workspace }}/SLiM
      #     key: ${{ runner.os }}-build_SLiM-${{ hashFiles('/d/a/SLiM.zip') }}
      #
      # - name: Cache SLiM on non-Windows
      #   id: cache-slim
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ${{ github.workspace }}/SLiM_build
      #       ${{ github.workspace }}/SLiM
      #     key: ${{ runner.os }}-build_SLiM-${{ hashFiles('SLiM.zip') }}

      - name: Setup cmake on non-Windows
        if: runner.os != 'Windows' && matrix.config.slim == 'yes'
        uses: jwlawson/actions-setup-cmake@v1.14

      - name: Install SLiM on Windows Part 1
        if: runner.os == 'Windows' && matrix.config.slim == 'yes' #&& steps.cache-slim-win.outputs.cache-hit != 'true'
        continue-on-error: true
        shell: msys2 {0}
        run: |
          cd /d/a
          unzip -o SLiM.zip
          cd SLiM/windows_compat/gnulib
          touch --date="`date`" aclocal.m4 Makefile.am configure configure.ac config.h.in Makefile.in
          cd ../../..
          mkdir SLiM_build
          cd SLiM_build
          cmake -G"MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release ../SLiM
          make -j 2

      - name: Install SLiM on Windows Part 2
        if: runner.os == 'Windows' && matrix.config.slim == 'yes'
        shell: msys2 {0}
        run: |
          cd /d/a
          cd SLiM_build
          make install
          cd ..
          rm SLiM.zip

      - name: Install SLiM on non-Windows Part 1
        if: runner.os != 'Windows' && matrix.config.slim == 'yes' #&& steps.cache-slim.outputs.cache-hit != 'true'
        continue-on-error: true
        run: |
          cd ${{ github.workspace }}
          unzip -o SLiM.zip
          mkdir SLiM_build
          cd SLiM_build
          cmake -DCMAKE_BUILD_TYPE=Release ../SLiM
          make

      - name: Install SLiM on non-Windows Part 2
        if: runner.os != 'Windows' && matrix.config.slim == 'yes'
        run: |
          cd ${{ github.workspace }}/SLiM_build
          sudo make install
          cd ..
          rm SLiM.zip

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install gdal

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        if: runner.os == 'Windows'
        env:
          SLIM_PATH: 'C:/Program Files (x86)/SLiM/bin/slim.exe'
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'

      - uses: r-lib/actions/check-r-package@v2
        if: runner.os != 'Windows' && matrix.config.conda == 'yes'
        env:
          SLIM_INSTALL: 1
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'

      - uses: r-lib/actions/check-r-package@v2
        if: runner.os != 'Windows' && matrix.config.conda == 'no'
        with:
          args: 'c("--no-manual", "--as-cran")'
          error-on: '"error"'

      - name: Upload test objects for covr
        if: runner.os == 'Linux' && matrix.config.slim == 'yes'
        uses: actions/upload-artifact@master
        with:
          name: covr-test-objects
          path: ~/covr_test_objects
          retention-days: 1

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-${{ matrix.config.r }}-slim-${{ matrix.config.slim }}-conda-${{ matrix.config.conda }}-results
          path: check
